### PR TITLE
FISH-464 Revert

### PR DESCRIPTION
**Pull request by Pandrex247**
We believe this PR is causing the JAXR TCK to fail.
https://github.com/payara/patched-src-grizzly/pull/26

### CODE REVIEW

**Comment by Pandrex247** [comment]
Note that since this reverts David's fix for an HTTP2 test, the build tests fail again now.

**Comment by Pandrex247** [comment]
Also includes version incremenets.
Tag here: https://github.com/payara/patched-src-grizzly/tree/2.4.4.payara-p6

**Review by MattGill98 — APPROVED** [review]

**Comment by dmatej** [comment]
> Note that since this reverts David's fix for an HTTP2 test, the build tests fail again now.

The same changes in Eclipse's version 3.0.0 passed all TCK tests in GlassFish (except jakarta package names), so how it could cause issues in Payara?

**Comment by dmatej** [comment]
Sad you didn't tell me, I could try to reproduce it.

**Comment by dmatej** [comment]
JAXR TCK nightly result of 5.2021.1-RC1 on my machine, so I believe the cause is something else (JDK version? Another race condition? (unusual in TCK as these tests are mostly single threaded)):
image
I will start it once more with different CPU settings. But if you can send me a link to logs on jenkins, it would simplify diagnostic of the real cause.

**Pull request merged**
